/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ContractAddresses_1337 } from './1337'
export type ContractAddressesKey = keyof typeof ContractAddresses
export const ContractAddresses = {
  1337: ContractAddresses_1337,
}
